---
title: QUIZ
timezone: UTC
collections:
  quiz:
    title: Quiz
    output: true
defaults:
- scope:
    path: ''
    type: quiz
  values:
    layout: quiz
description: Coloque descrição aqui
baseurl: "/art-quiz"
url: http://objetivoweb.com.br
markdown: kramdown
sass:
  style: compressed
plugins:
- jekyll-coffeescript
