---
title: QUIZ Obras de arte
timezone: UTC
collections:
  obras:
    title: Obras
    output: true
defaults:
- scope:
    path: ''
    type: obras
  values:
    layout: null
description: Coloque descrição aqui
baseurl: "/art-quiz"
url: http://objetivoweb.com.br
markdown: kramdown
sass:
  style: compressed
plugins:
- jekyll-coffeescript
